### ISSUE TITLE
Incorporate JSON reformatting directly in the readers

### ISSUE THREAD

**Issue by jsquyres** [jsquyres/hwloc#1]
Per https://github.com/jsquyres/hwloc/commit/38c39d6edd288394afe692b84d004307208fa0e1#commitcomment-7582909, incorporate the functionality of these two files into the readers:

./netloc_reader_ib/Perl_IB_support.pm
./netloc_reader_of/Perl_OF_support.pm

**Comment by jjhursey** [comment]
_(Note to future self)_
Consider having the perl front-end parsers produce JSON compatible with the static reader. This will consolidate quite a bit of code in the readers.

**Comment by jjhursey** [comment]
netloc seems to have bit rotted from lack of cycles. Let's close this as it is probably not relevant any longer.
